# This file configures the analyzer for the Maison Al Teeb Flutter app.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    use_super_parameters: false
    overridden_fields: false
    prefer_const_constructors: false
    unnecessary_cast: false
