-- Morocco localization foundation
alter table if exists public.sales add column if not exists amount_received numeric(12,2) default 0 check (amount_received >= 0);
alter table if exists public.sales add column if not exists change_amount numeric(12,2) default 0 check (change_amount >= 0);
alter table if exists public.sales add column if not exists receipt_number bigint generated by default as identity;
alter table if exists public.sales add column if not exists receipt_notes text;
alter table if exists public.products add column if not exists name_ar text;
alter table if exists public.products add column if not exists name_fr text;
alter table if exists public.products add column if not exists sku text;
alter table if exists public.products add column if not exists image_url text;
create unique index if not exists products_user_sku_unique on public.products(user_id, sku) where sku is not null and sku <> '';
